modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/rosevcook/windswept/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "windswept"
    version = "2.2.2"
    displayName = "Windswept"
    logoFile = "logo.png"
    itemIcon = "windswept:holly_berries"
    configBackground = "windswept:textures/block/holly_log.png"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/windsweptmod"
    authors = "Rose"
    description = '''A general expansion to snowy and forest areas of the game, incentivising players to explore and build in the new expanded areas'''

[[dependencies.windswept]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.windswept]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.windswept]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.0,)"
    ordering = "BEFORE"
    side = "BOTH"
